JovemProgramadorMvc/Controllers/AlunoController.cs
using JovemProgramadorMvc.Data.Repositorio.Interfaces;
using JovemProgramadorMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace JovemProgramadorMvc.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IAlunoRepositorio _alunorepositorio;

        public AlunoController(IConfiguration configuration, IAlunoRepositorio alunoRepositorio)
        {
            _configuration = configuration;
            _alunorepositorio = alunoRepositorio;
        }

        public IActionResult Index(AlunoModel filtroAluno)
        {
           List<AlunoModel> aluno = new();

                aluno = _alunorepositorio.BuscarAlunos();

            if (filtroAluno.Idade > 0)
            {
                aluno = _alunorepositorio.FiltroIdade(filtroAluno.Idade, filtroAluno.Operacao);
                return View(aluno);
            }
            if (filtroAluno.Nome != null)
            {
                aluno = _alunorepositorio.FiltroNome(filtroAluno.Nome);
                return View(aluno);
            }
            if (filtroAluno.Contato != null)
            {
                aluno = _alunorepositorio.FiltroContato(filtroAluno.Contato);
                return View(aluno);
            }

            return View(aluno);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Mensagem()
        {
            return View();
        }

        public async Task<IActionResult> BuscarEndereco(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.BuscarId(aluno.Id);
            aluno = retorno;
            EnderecoModel enderecoModel = new();
            try
            {
                var cep = aluno.Cep.Replace("-", "");

                using var client = new HttpClient();
                var result = await client.GetAsync(_configuration.GetSection("ApiCep")["BaseUrl"] + cep + "/json");

                if(result.IsSuccessStatusCode)
                {
                    enderecoModel = JsonSerializer.Deserialize<EnderecoModel>(
                        await result.Content.ReadAsStringAsync(), new JsonSerializerOptions() { });

                    //validação
                    if (string.IsNullOrWhiteSpace(enderecoModel.complemento))
                    {
                        enderecoModel.complemento = "Nenhum";
                    }

                    if (string.IsNullOrWhiteSpace(enderecoModel.logradouro))
                    {
                        enderecoModel.logradouro = "Nenhum";
                    }

                    if (string.IsNullOrWhiteSpace(enderecoModel.bairro))
                    {
                        enderecoModel.bairro = "Nenhum";
                    }
                    enderecoModel.IdAluno = aluno.Id;
                    _alunorepositorio.InserirEndereco(enderecoModel);
                }

                else
                {
                    ViewData["Mensagem"] = "Erro na busca do endereço!";
                    return View("Index");
                }
                
            }
            catch(Exception e)
            {

            }


            return View("BuscarEndereco", enderecoModel);
        }


        [HttpPost]
        public IActionResult Inserir(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.Inserir(aluno);
            if (retorno != null)
            {
                TempData["Mensagem2"] = "Dados gravados com sucesso!!";
            }
            return RedirectToAction("Index");

        }

        public IActionResult BuscarAlunos(AlunoModel aluno)
        {
             _alunorepositorio.BuscarAlunos();
            return RedirectToAction("Index");
        }


        public IActionResult Editar(int id)
        {
            var aluno = _alunorepositorio.BuscarId(id);
            return View("Editar",aluno);
        }

        public IActionResult Atualizar(AlunoModel aluno)
        {
            var retorno = _alunorepositorio.Atualizar(aluno);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            var retorno = _alunorepositorio.Excluir(id);
            if (retorno == true)
            {
                TempData["MensagemExcluir"] = "Dados Excluido com Sucesso!";
            }
            else
            {
                TempData["MensagemNaoExcluir"] = "Erro em Excluir Dados do Aluno!";
            }
            return RedirectToAction("Index");
        }

    }
}

JovemProgramadorMvc/Controllers/FiltrosController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace JovemProgramadorMvc.Controllers
{
    public class FiltrosController : Controller
    {
        public FiltrosController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

JovemProgramadorMvc/Views/Aluno/Adicionar.cshtml
@model AlunoModel
@if (TempData["Mensagem2"] != null)
{
    <div class="alert-success col-4">
        @TempData["Mensagem2"]
    </div>
}

<form asp-controller="Aluno" asp-action="Inserir" method="post">
    <div class="mb-3">
        <label for="NomeInput" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control col-6" />
    </div>
    <div class="mb-3">
        <label for="IdadeInput" class="form-label">Idade</label>
        <input type="text" asp-for="Idade" class="form-control col-1" />
    </div>
    <div class="mb-3">
        <label for="ContatoInput" class="form-label">Contato</label>
        <input type="text" asp-for="Contato" class="form-control col-3" placeholder="(00) 00000-0000" />
    </div>
    <div class="mb-3">
        <label for="EmailInput" class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control col-3" />
    </div>
    <div class="mb-3">
        <label for="CEPInput" class="form-label">CEP</label>
        <input type="text" asp-for="Cep" class="form-control col-3" placeholder="00000-000" />
    </div>

    <div class="text-center">
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
    </div>
</form>

JovemProgramadorMvc/Views/Aluno/BuscarEndereco.cshtml
@model EnderecoModel
<form>
    <div class="mb-3">
        <label for="LogradouroInput" class="form-label">Logradouro</label>
        <input type="text" class="form-control col-5" asp-for="logradouro" />
    </div>
    <div class="mb-3">
        <label for="ComplementoInput" class="form-label">Complemento</label>
        <input type="text" class="form-control col-5" asp-for="complemento" />
    </div>
    <div class="mb-3">
        <label for="BairroInput" class="form-label">Bairro</label>
        <input type="text" class="form-control col-3" asp-for="bairro" />
    </div>
    <div class="mb-3">
        <label for="LocalidadeInput" class="form-label">Localidade</label>
        <input type="email" class="form-control col-3" asp-for="localidade" />
    </div>
    <div class="mb-3">
        <label for="UfInput" class="form-label">Uf</label>
        <input type="text" class="form-control col-1" asp-for="uf" />
    </div>
    <div class="mb-3">
        <label for="DDDInput" class="form-label">DDD</label>
        <input type="text" class="form-control col-1" asp-for="ddd" />
    </div>
    <div class="text-center">
        <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
    </div>
</form>

JovemProgramadorMvc/Views/Aluno/Editar.cshtml
@model AlunoModel



@if (TempData["Mensagem2"] != null)
{
<div class="alert-success col-4">
    @ViewData["Mensagem2"]
</div>}



<form asp-controller="Aluno" asp-action="Atualizar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="name" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control col-md-6" required>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Idade</label>
        <input type="text" asp-for="Idade" class="form-control col-md-1">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Contato</label>
        <input type="text" asp-for="Contato" class="form-control col-md-2" placeholder="(00) 00000-0000">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Email</label>
        <input type="email" asp-for="Email" class="form-control col-md-2">
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Cep</label>
        <input type="text" asp-for="Cep" class="form-control col-md-2">
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary col-1" role="button">Atualizar</button>
        <a class="btn btn-primary col-1" role="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
    </div>
</form>

JovemProgramadorMvc/Views/Aluno/Index.cshtml
@model List<AlunoModel>

@if (ViewData["Mensagem"] != null)
{
<div class="alert-danger col-4">
    @ViewData["Mensagem"]
</div>
}

@if (TempData["Mensagem2"] != null)
{
<div class="alert alert-success col-4">
    @TempData["Mensagem2"]
</div>
}

<div class="text-lefrt">

    <div>
        <h1>Dados dos Alunos</h1>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">Idade</th>
                <th scope="col">Contato</th>
                <th scope="col">E-mail</th>
                <th scope="col">Cep</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (AlunoModel aluno in Model)
                {
                    <tr>
                        <th scope="row">@aluno.Id</th>
                        <td>@aluno.Nome</td>
                        <td>@aluno.Idade</td>
                        <td>@aluno.Contato</td>
                        <td>@aluno.Email</td>
                        <td>@aluno.Cep</td>
                        <td>
                            <div class="d-grid gap-2 d-md-flex justify-content-left">
                                <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="BuscarEndereco" asp-route-id="@aluno.Id">Endereço</a>
                            </div>
                        </td>


                        <td>
                            <div class="d-grid gap-2 d-md-flex justify-content-left">
                                <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Editar" asp-route-id="@aluno.Id">Editar</a>
                            </div>
                        </td>

                        <td>
                            <div class="d-grid gap-2 d-md-flex justify-content-left">
                                <a class="btn btn-danger" type="button" asp-controller="Aluno" asp-action="Excluir" asp-route-id="@aluno.Id">Excluir</a>
                            </div>
                        </td>
                    </tr>
                }

            }
        </tbody>
    </table>


    <div class="text-center">
        <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Adicionar">Adicionar Novo Aluno</a>
        <a class="btn btn-primary" type="button" asp-controller="Filtros" asp-action="Index">Filtrar</a>
    </div>

</div>

JovemProgramadorMvc/Views/Aluno/Mensagem.cshtml
<div class="text-center">
    <h1>Adicionado com Sucesso</h1>
    <p>Novo aluno adicionado</p>
</div>
<div class="d-grid gap-2 d-md-flex justify-content-center">
    <a class="btn btn-primary" type="button" asp-controller="Aluno" asp-action="Index">Voltar</a>
</div>